### ISSUE TITLE
[request] Firefox version

### ISSUE THREAD

**Issue by bryce-lynch** [fanfare/googleimagesrestored#1]
Please port this extension to Firefox.

**Comment by fanfare** [comment]
Have packaged and signed the latest version as a Firefox extension, available [here](https://github.com/fanfare/googleimagesrestored/raw/master/dist/google_images_restored-0.0.2-fx.xpi). Will hopefully be in the Mozilla store to download from there soon.

**Comment by bryce-lynch** [comment]
Thanks!
