### ISSUE TITLE
Features missing: larger than, exact size filter options

### ISSUE THREAD

**Issue by mzso** [fanfare/googleimagesrestored#12]
Hi!

This addon was much needed.
However I noticed the filter options to "larger than" and "exact size", which the new layout removed are not restored.

**Comment by fanfare** [comment]
'exact size' should be available in version 0.1.3 -- still need to test it more to make sure its bug free. i might do 'larger than 'later but there's a different extension which does that so I'm not really prioritizing it rn.

**Comment by mzso** [comment]
[**@fanfare**](https://github.com/fanfare) commented on [2019. szept. 5. 23:51 CEST](https://github.com/fanfare/googleimagesrestored/issues/12#issuecomment-528604023 "2019-09-05T21:51:22Z - Replied by Github Reply Comments"):
> 'exact size' should be available in version 0.1.3 -- still need to test it more to make sure its bug free. i might do 'larger than 'later but there's a different extension which does that so I'm not really prioritizing it rn.

Really? For Firefox as well? Where can I find it?

**Comment by fanfare** [comment]
ya - https://addons.mozilla.org/en-US/firefox/addon/google-images-restored

**Comment by mzso** [comment]
[**@fanfare**](https://github.com/fanfare) commented on [2019. szept. 6. 01:14 CEST](https://github.com/fanfare/googleimagesrestored/issues/12#issuecomment-528642036 "2019-09-05T23:14:18Z - Replied by Github Reply Comments"):
> ya - [https://addons.mozilla.org/en-US/firefox/addon/google-images-restored](https://addons.mozilla.org/en-US/firefox/addon/google-images-restored)

?
That's this addon. You mentioned one that restores the "larger than" option.

**Comment by fanfare** [comment]
pasted the wrong one https://addons.mozilla.org/en-US/firefox/addon/google-image-sizer/

**Comment by mzso** [comment]
[**@fanfare**](https://github.com/fanfare) commented on [2019. szept. 6. 03:28 CEST](https://github.com/fanfare/googleimagesrestored/issues/12#issuecomment-528669732 "2019-09-06T01:28:57Z - Replied by Github Reply Comments"):
> pasted the wrong one [https://addons.mozilla.org/en-US/firefox/addon/google-image-sizer/](https://addons.mozilla.org/en-US/firefox/addon/google-image-sizer/)

Thanks. Although that addon seems to be non-functinal. If I chose any of the xMP options the "icon" option ends up being selected. And the xMP options disappear on the new results page.
