### ISSUE TITLE
Request: Restore "search by image" option as well

### ISSUE THREAD

**Issue by mzso** [fanfare/googleimagesrestored#13]
Hi!

I've been using the [View Image](https://addons.mozilla.org/en-US/firefox/addon/view-image/?src=external-Add-ons_Manager_Context_Menu-extension) addon to restore View Image and Search by Image buttons.
(It also has a hider referrer option when clicking view image, not sure how useful this is, but I think I saw before that some sites blocked the loading of the image when I opened it from google search.)

Now this addon does restore the the former but not the latter. It would be nice to have the search by image option back as well at its usual place.
Also the two addons don't seem to be compatible, so the option is not restored even if I have that addon enabled.

**Comment by fanfare** [comment]
Where is the 'usual place' for search by image?

**Comment by mzso** [comment]
Next to the website name, as shown on this image:

![kép](https://user-images.githubusercontent.com/4479090/64389300-5b518980-d042-11e9-93f7-bbb7f31ed42e.png)

**Comment by fanfare** [comment]
im not sure what firefox provides, but chrome has had 'search by image' in the right click menu for images for quite some times, and i have always used that; so i think i'm going to just keep it as is for the time being
