### ISSUE TITLE
Able to trigger google image search in the old layout

### ISSUE THREAD

**Issue by Procyon-b** [fanfare/googleimagesrestored#20]
sort of...

For the third time in several days I was able to get google.com to issue a new NID cookie with the old layout attached to it.
Unfortunately I'm unable to trigger/reproduce with a specific recipe.

About a week ago I discovered this extension and tried the script in tampermonkey to see the end result. Since some things are still a little bit broken, I had the idea to use a clean profile to test google image search with other user-agents.
Using google's extension I've seen that some old browsers (IE, old Opera) trigger the very very old (and simple) layout. I've searched for some very old chrome UA strings and tried them, until I reached v5 and got the layout that this extension tries to reproduce. But it was probably only a coincidence  :( , since I have been unable to reproduce this (and I erased the cookie forgetting to backup them - shame on me). Every day since then I have booked 15min of my time to try again, cleaning stored data, changing UA, searching, rince & repeat...

Thursday, good news, I got a NID with the old layout. Friday nothing, today (saturday) nothing, till 10 min ago, where I got another NID in my normal profile while in incognito mode without even trying (no spoofed UA).

I will keep trying and gather more NIDs.
Currently I can give one of these NID to @fanfare (in private). You can use it any way you feel, I won't use it anymore. It's yours. I think you'll have to explore the css pages and js files used in this layout, and try to find how you can modify the current files with your userscript. I feel that the previous layout might one day not be accessible at all. This extension will then be the unique solution.   ;)

**Comment by fanfare** [comment]
your post got me curious about this situation -- I managed to find an old NID cookie archived on webrecorder.io which reproduces exactly what you found.. extremely interesting, and surprised that still works. you can reach me at rene@jollo.org if you ever feel like chatting more about it.
