### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by ultracoolboy** [fanfare/googleimagesrestored#22]
As of 10-23-2019 The extention has stopped working and now I'm back to seeing the shitty new layout, I just wanted to inform this in case it stopped working for anyone else, I hope this is temporary.

**Comment by fanfare** [comment]
Clear your cookies for google.com.. that will fix it (this unfortunately has happened to some other people too, but clearing cache/cookies brings it back), the extension is still working on my end.

**Comment by ultracoolboy** [comment]
seems like when my cookies are cleared and im logged out only then the
extension works from my end.

**Comment by fanfare** [comment]
if you clear your cookies, then log in, does it stop working again?

**Comment by ultracoolboy** [comment]
pretty much
