### ISSUE TITLE
dose not work when i'm logged into my google account 

### ISSUE THREAD

**Issue by ultracoolboy** [fanfare/googleimagesrestored#23]
When I'm logged in the extension dose not work for me anymore, I then clear all my cookies and get logged out and then it works but then I log back into my google account it then stops working 
here screen shots showing it

![](https://i.imgur.com/SNALbQc.png)

https://imgur.com/a/SO98Ll4

![](https://i.imgur.com/hs7fIvy.png)

**Comment by fanfare** [comment]
yeah theyre defnitely messing with some new junk
i was finally able to replicate this situation in a virtual machine and all of the hashed classnames are all different, and none of the techniques i used to make this extension possible work any more if they implement that new change permanently.
i could create something that grabs a known good (working) NID cookie and then swap it out when the extension swaps working to restore order. who knows how long that would last though.

**Comment by ultracoolboy** [comment]
alright thx, Sorry if this post was a bother but Idk if I was that clear in
my last post, but yea hope it works out sooner or later.

**Comment by fanfare** [comment]
nah its cool, im just frustrated too because i dont want this thing to break lol. the side layout format is trash

**Comment by Sxderp** [comment]
Blame "webpack" and "scoped css". I can see some benefit but from a flexibility standpoint it just pisses me off.

**Comment by MMOtte** [comment]
I guess the temporary fix for the user is to enable this add-on in private browsing, then open an incognito tab to imagesearch. 

God I hate pointless redesigns.

**Comment by Smorvel** [comment]
Same problem for months... tired of waiting for a fix.. 

@fanfare Can other extension developer use your code on his extension? I sujest him to use it, but him say that your license not allow it...

**Comment by fanfare** [comment]
updated to 0.2.0
