### ISSUE TITLE
Doesn't seem to work in private windows

### ISSUE THREAD

**Issue by pj-camp** [fanfare/googleimagesrestored#28]
And I have allowed it to do so. This is with Firefox v. 71.0 64 bit running on Windows 10.

**Comment by Hikaru4v** [comment]
It works fine for me [**_P O O F_**](blob:https://imgur.com/99d46bb9-dacf-487c-b65b-c0cbe98f98a7)

**Comment by fanfare** [comment]
updated to 0.2.0
