### ISSUE TITLE
Doesn't work in Chrome Canary anymore

### ISSUE THREAD

**Issue by Pearate** [fanfare/googleimagesrestored#30]
This extension is great and worked in Chrome Canary the last year but not anymore, I would say since November or December. 
Do you think you can fix it ? 
Thanks 

Version 81.0.4018.0 (Build officiel) canary (64 bits)

**Comment by gitinho** [comment]
Also not working, firefox 71.0

**Comment by Sparkpin** [comment]
Works for me on Chrome 79.0.3945.117 (Official Build) (64-bit) after clearing NID cookie; this might be some new breaking change in Chrom{e,ium} if clearing that cookie does not help
