### ISSUE TITLE
dose not work anymore in 2020

### ISSUE THREAD

**Issue by ultracoolboy** [fanfare/googleimagesrestored#31]
besides the extension not working no matter how many times I clear the cookies back and fourth (still only works when I'm signed out of my google account) but like half the image results only show up so I have to actually get rid of the extension if I want to see the rest of the image search results but yea still not working and I honestly hate google.

**Comment by GianniGi** [comment]
agreed

**Comment by GianniGi** [comment]
it works for me under firefox 68.0 (first install)
maybe try with a new profile? start with firefox -p

**Comment by fanfare** [comment]
updated to 0.2.0

**Comment by fanfare** [comment]
updated extension to 0.2.0
