### ISSUE TITLE
Higher resolution images not being pulled down on Firefox.

### ISSUE THREAD

**Issue by ak2766** [fanfare/googleimagesrestored#34]
I've noticed a difference between the latest version of the add-on in Firefox (as compared to the Chrome extension) - it is no longer pulling down higher resolution images.  For instance, I searched for `cockpit ubuntu` on Firefox and Chrome, then clicked on this image:
![Selection_00186](https://user-images.githubusercontent.com/6629646/74094109-d65a2700-4b2f-11ea-8d43-1183f2ea71c0.png)

Firefox takes me to this [URL](https://www.google.com/search?q=ubuntu+cockpit&sxsrf=ACYBGNR1RsU3oUZoJ7uRv-U72mlMiN6BTA:1581207107847&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjj3-q_l8PnAhWlguYKHXegArYQ_AUoAXoECA4QAw&biw=1920&bih=960).
Chrome takes me to this [URL](https://www.google.com/search?q=ubuntu+cockpit&sxsrf=ACYBGNRUpfGH1BkwsxfSL0GH2lPkPI9iBQ:1581208012262&source=lnms&tbm=isch&sa=X&ved=2ahUKEwit8IvvmsPnAhWG6nMBHcKSBkMQ_AUoAXoECA4QAw&biw=1920&bih=952).

As you can see, the Firefox image never sharpens as it has pulled in what appears to be a thumbnail image while Chrome pulls in the high resolution image.

Firefox is running version: 0.2.2
Chrome is running version: 0.2.1

Appears to be a regression and as such I'm reluctant to upgrade the Chrome extension being that it'll most likely end up in the same situation as the Firefox add-on.

**Comment by fanfare** [comment]
I don't believe it is a difference between 0.2.2 and 0.2.1 -- I think it is something else. An entirely different strategy was needed for getting the full-size Image URL for firefox, because of some weird permission errors. It is possible that it isn't working any more, although it is still working fine on my version of firefox, even the 0.2.2 version. What version of firefox are you running?

**Comment by fanfare** [comment]
If you want to try to debug it in firefox, search for an image and then in your js console type
`document.querySelectorAll(`c-wiz.P3Xfjc`)[0].__jscontroller.o.H[0].Cf.j[0].j[3][0].j[2].j[3].H[0]`
and see if it returns a string that starts with `https://encrypted-tbn0.gstatic.com1`
if it does, then type
`document.querySelectorAll(`c-wiz.P3Xfjc`)[0].__jscontroller.o.H[0].Cf.j[0].j[3][0].j[2].j[4].H[0]`
and see if that has the full size image. if it does then I need to investigate further -- but if it returns `undefined` or throws an error.. then something has changed yet again on Google's back end. The extension has two failsafes in case that method doesnt work, but those failsafes unfortunately are only working in Chrome.

**Comment by ak2766** [comment]
I'm Firefox version 72.0.2:
![About Mozilla Firefox_00187](https://user-images.githubusercontent.com/6629646/74094804-6f426f80-4b3b-11ea-988f-23752c315e8c.png)

**Comment by ak2766** [comment]
> but if it returns `undefined` or throws an error..

Yup, it is throwing an error - excuse me if I entered this is in the wrong location - I'm not too versed with the developer tools:
![Selection_00188](https://user-images.githubusercontent.com/6629646/74094873-67cf9600-4b3c-11ea-9239-cdce03b813f4.png)

**Comment by ak2766** [comment]
I have to agree - something is changing even as we speak - I could see images in the **_Related images_** section but now it appears empty.

Cat and mouse with Google I guess...

**Comment by fanfare** [comment]
ok, that is actually good news. because if it was not throwing any errors then i would be stumped.  at least i can maybe consider a different strategy to maybe futureproof it with some heuristics or something, depending on what changes they just made i'll see. ill take a look at it tomorrow, thanks for your help!

**Comment by fanfare** [comment]
i have a feeling this thing is gonna be 10000% broken like imminently.. ughhhhhh. the method to get it working the second go around is so much more fragile and flaky than the first

**Comment by ak2766** [comment]
Cool - sounds like you've got a plan in place.  Let me know if you need me to test out before you release...

**Comment by ak2766** [comment]
More info:

Appears that in an incognito session, the higher resolution image eventually makes it through.  Now it seems that an interaction with another add-on is causing dramas for me.  However, **_Related images_** remains empty...

**Comment by ak2766** [comment]
I'm getting very intermittent behaviour in Firefox.  After disabling all add-ons and leaving just Google Images Restored enabled, and after restarting browser 2 times, I can now see **_Related images_** - Yay.

However, that first image I click on never resolves to a higher resolution image.  Clicking on images in the **_Related images_** section results in majority showing the higher resolution image.  I thought that maybe clicking around those related ones then clicking back on that first image might bring in the higher resolution one, but no dice.

But now there's a - BIG DISCOVERY!

An image in the **_Related images_** section that also appears in the search results has different behaviour when clicked on.  For instance, have a look at this screenshot:
![Selection_00189](https://user-images.githubusercontent.com/6629646/74096191-a7ec4400-4b4f-11ea-8963-eec3c0957c88.png)

When I click on image `B`, I cannot get a high resolution.  However, when I click on image `A`, I can see image `B` in the **_Related images_** section and when I click on that one, I get a high resolution of image `B` - go figure!

**Comment by fanfare** [comment]
this is because the 'related images' are fetched from google via an ajax request, and the response contains the exact hi-res URL for those images. the NATIVE images on the page, however, only have the high res information embedded in that cobweb of google's 'jscontroller' stuff. (the initial images on the page actually have some of it in the HTML but images loaded as you keep scrolling down don't have an easy way of getting the high res information)

**Comment by ak2766** [comment]
Whoa - how convoluted is that?  I find it odd that Google contributes so much to open source but makes it utterly hard for you add-on developers...

**Comment by fanfare** [comment]
well in all fairness i think this kind of thing is the last thing google wants.. an extension (that people seem to want) that detracts from their new version, which is primarily more of an advertising scheme (product comparison, shopping, etc). so its no wonder theyre making it tricky, prob so people wont mess with it!

**Comment by ak2766** [comment]
But most of their _new versions_ are counter intuitive like for instance that which necessitates your add-on...

**Comment by fanfare** [comment]
i'm unfortunately unable to reproduce the issue youre having with my version of firefox (same as yours).. i assume this is just more A/B testing and its a unique situation. if you have a sec and want to mess with it further would you mind sharing the contents of what `document.querySelectorAll('c-wiz')` says? it should be a NodeList , click the > next to it and then highlight the results and paste it here, like this: 

0: <c-wiz jsrenderer="eFjyv" jsshadow="" jsdata="deferred-i1" data-p="%.@.\"aol\",\"isch\",null,null,null,false,2]\n" data-node-index="0;0" jsmodel="hc6Ubd">​
1: <c-wiz class="Wdq1db" jsrenderer="tEsszb" jsshadow="" jsdata="deferred-i2" data-p="%.@.null,2]\n" data-node-index="1;0" jsmodel="hc6Ubd">​
2: <c-wiz class="P3Xfjc SSPGKf BIdYQ FA7L0b zE3eif" jsrenderer="Ips5vc" data-ssc="0" jsdata="deferred-i3" data-p="%.@.[\"aol\",null,null,n….com\",\"\",4,true]\n]\n" jscontroller="UKPnme" jsaction="rcuQ6b:npT2md;mBqKme:Fv7…e:bl5Wke;d9N7hc:rFngrd;" data-node-index="0;0" jsmodel="hc6Ubd turbqb" view="">​
3: <c-wiz class="Npn1i" jsrenderer="mqKLR" jsdata="deferred-i4" data-p="%.@.]\n" data-node-index="5;0" jsmodel="hc6Ubd">​
4: <c-wiz class="ymoOte" jsrenderer="rOY9Fc" jsshadow="" jsdata="deferred-i5" data-p="%.@.]\n" data-node-index="3;0" jsmodel="hc6Ubd">

**Comment by fanfare** [comment]
or actually just using pastebin would be better, it messes it up here

**Comment by fanfare** [comment]
and yeah i agree with you, the new google images makes no sense. it is utterly the worst

**Comment by ak2766** [comment]
Hmm - that is proving difficult for me - not being versed with how to appropriately use developer tools - I'd be more than willing to share a zoom or teamviewer session - whichever you prefer

**Comment by fanfare** [comment]
OK - im installing teamviewer right now. you can e-mail me at aehtyb@gmail.com if you need to exchange desktop key info

**Comment by ak2766** [comment]
I managed to: https://pastebin.com/3Uqh4Cwm

**Comment by fanfare** [comment]
oh - cool thanks.

**Comment by ak2766** [comment]
Hmm - I see you have a personal IRC server - maybe I can head over there for faster comms...

**Comment by fanfare** [comment]
yes , irc.jollo.org ssl port 9999 - im on there as fanfare

**Comment by ak2766** [comment]
Apologies, I was just about to reply to you in irc then I lost power and internet went offline. Will be back when it returns...

**Comment by MisterIkkus** [comment]
I'm having the same issue. Glad to see it's already been reported. Thanks for working on it.

**Comment by fanfare** [comment]
looked into it, pushed a bugfix, 0.2.3 full size images ok in firefox now
