### ISSUE TITLE
Low resolution previews

### ISSUE THREAD

**Issue by rynodigital** [fanfare/googleimagesrestored#38]
Browser:  Brave
Version: 0.2.3

When using google images, every image I click on is previewed in low resolution.  When i right click and open the image in a new tab it's at / around 225px regardless of the image selected.

Clicking the 'view image' button yields an about:blank page across the board as well

<img width="1181" alt="Screen Shot 2020-02-21 at 11 40 55 AM" src="https://user-images.githubusercontent.com/47394232/75061965-0cd46200-549f-11ea-83fb-924fb8c2a356.png">

**Comment by fanfare** [comment]
fixed in 0.2.4
