### ISSUE TITLE
Images only showing as checker boxes when clicking on full size image 

### ISSUE THREAD

**Issue by MattySolja** [fanfare/googleimagesrestored#42]
as title says when i try to click the image to see it bigger and use arrow keys to browse it loads a low res version then changes to a white and gray checker box.
I have checked without the extension and it works just in the horrible format

thanks :)

**Comment by fanfare** [comment]
hi.. having trouble reproducing this locally; maybe could be some A/B testing going on; can you give me a search term to try so i can search with it and maybe see if i can reproduce exactly what youre experiencing
