### ISSUE TITLE
Loading bar not exist 

### ISSUE THREAD

**Issue by semosemo941** [fanfare/googleimagesrestored#45]
please add loading bar just like what it was
its helpful for slow internet connection owner like me 😍

**Comment by fanfare** [comment]
hi semo; i dont think at this point i'm going to add any additional visual UI changes to this extension, primarily out of the fact that it would be a 'change' to how it is now that might irritate users that have already become accustomed to there *not* being a loading bar indicator.. if that makes sense. thank you for using the extension though.
