### ISSUE TITLE
Images stuck in negative/inverted color scale

### ISSUE THREAD

**Issue by roxxso** [fanfare/googleimagesrestored#46]
This appears to be happening when used in conjunction with FF addon 'Dark Theme for Google'
(https://addons.mozilla.org/en-US/firefox/addon/dark-theme-for-google/)
Some images load up normal and some will be in negative for a split second before showing up normally, however, a lot of the time the image is completely stuck in a negative state.  Not sure why or is there is a consistent factor, but toggling off either that addon or this addon corrects the color issue.  I'm not sure where the error lies within the addons, but just wanted to put something here to address it in case anyone is having similar issues using 'image restored' and a dark theme.

**Comment by fanfare** [comment]
i cant guarantee this will work with any other extension
