### ISSUE TITLE
Missing title/link and Visit button takes you to Google's UI (with specific scenario)

### ISSUE THREAD

**Issue by Poopooracoocoo** [fanfare/googleimagesrestored#47]
I searched for "isotope notation electrons" into Chrome's omnibox and then clicked on the first image of Google's card.
![image](https://user-images.githubusercontent.com/51363864/77999605-aafcf700-737e-11ea-8331-8a9d4ddb5a25.png)
![image](https://user-images.githubusercontent.com/51363864/77999464-6f622d00-737e-11ea-9a37-fed5a470f16d.png)
![image](https://user-images.githubusercontent.com/51363864/77999507-7ee17600-737e-11ea-873f-a79d32bbf4b3.png)

**Comment by Poopooracoocoo** [comment]
Also happens when you click on the images in the "Images for" section
![image](https://user-images.githubusercontent.com/51363864/78000494-172c2a80-7380-11ea-8461-6431768ba6cc.png)

**Comment by fanfare** [comment]
thanks just now seeing this i will take a look

**Comment by fanfare** [comment]
the missing title scenario should be resolved
