### ISSUE TITLE
Right third of screen is not working

### ISSUE THREAD

**Issue by cswanson1998** [fanfare/googleimagesrestored#51]
When I mouse over the right side of Google Images with the extension enabled, it sometimes no longer responds to clicks.

This is a new issue that has popped up within the past week and it only happens with some searches, seemingly at random.

**Comment by fanfare** [comment]
im seeing this consistently now with the following steps, can you do this and tell me if it happens to you?
google search (not image search, but regular search) 'potato'
see the thumbs in the results on the google search results page
click a thumb
it opens up google images, and the right side is unclickable

can you tell if if the first image in the image search results is the thumb that you clicked? google just changed their behavior and i need to adjust accordingly if this is happening for everyone else too

**Comment by fadster** [comment]
I have the same problem. For example, on rows with five thumbnails, the last two are not clickable. This has indeed started happening within the past ten days or so.

@fanfare I followed your steps and the first image in the search results is the one I clicked on, but it is not expanded and the page scrolls down until the image I clicked on is no longer visible. Also, the right side is not clickable.

Thank you for looking into this. I'm very grateful for this extension!

**Comment by cswanson1998** [comment]
@fanfare, I've replicated these and its happening as you say.

**Comment by fanfare** [comment]
I have a release 0.2.8 here that should fix this situation; it isn't up yet in the chrome web store so im not going to close this yet. if someone else can confirm this patch remedies the situation i will close the issue. thanks for letting me know about this

**Comment by fanfare** [comment]
i figure it is working now for all

**Comment by fadster** [comment]
I confirm, it is indeed working. Thanks a lot! :smiley:

**Comment by fadster** [comment]
@fanfare I'm seeing this bug again. It happens when the image you click on in the main results page doesn't show up as the first image in the image results when you click on it. For example, search for "Christa Miller" on the main search page (not image search). Click on the leftmost image in the resulting info box on the right of the results page. This will take you to the image results page but the image you clicked on isn't the first one on the page. Notice then that the right third of the page is not clickable.

**Comment by fanfare** [comment]
sorry for the delay. been without internet for a month (hurricane laura) and still dont have internet in the city yet, at a hotspot right now. i just confirmed this is a thing and found a fix but am not sure when i will be able to make a new package with the fix and post it again. if you have ublock, you can block `#islsp` on the page, so the ublock filter would be `###islsp` - that will hide the right side 'unclickable' area.

**Comment by fadster** [comment]
@fanfare I hope the internet is the only thing you lost to the hurricane! Your workaround does the job. Thanks!

**Comment by fanfare** [comment]
added css to hide that unclickable region in 0.3.1
