### ISSUE TITLE
Larger previews

### ISSUE THREAD

**Issue by anonimuos** [fanfare/googleimagesrestored#54]
Excellent extension. 1 request to the developer is on high DPI screens, show the images a little larger still. On my 17 inch laptop which has high-res, high DPI screen, I've turned on display scaling, zoom etc but the image preview shown is still a little small with plenty of space above and below it wasted. Around 1.5 inches on top and bottom of the image unused. It would be nice (even if the original Google Image search didn't have it), if the image was scaled to fit the vertical resolution/height of the screen.

**Comment by fanfare** [comment]
At this point i don't think i'm going to change the UI because it might be unwelcome for people that are already used to the way it is right now..
