### ISSUE TITLE
POLL: SHOULD THE NEW STICKY HEADER BE REMOVED BY THIS EXTENSION?

### ISSUE THREAD

**Issue by fanfare** [fanfare/googleimagesrestored#55]
Opening this up for 1 week in case anyone sees it.
Google has now added a 'sticky' header when you scroll down on google images.
It can be removed with CSS but this is a new change that I wonder if it should be eliminated within this extension since it isnt in line with the Aug 2019 layout.
It looks like this

https://i.imgur.com/s8PKuxs.png

Any input appreciated, thanks

**Comment by Sxderp** [comment]
I haven't seen it. Doesn't bother me too mcuh. It's surprising Google hasn't done this previously.

**Comment by fanfare** [comment]
thanks for the input
