### ISSUE TITLE
Descriptions of images are missing

### ISSUE THREAD

**Issue by JThiner1997** [fanfare/googleimagesrestored#57]
the Descriptions of images are missing, can you please find out what's wrong?

**Comment by fanfare** [comment]
attempted to fix in 0.3.1, not sure how stable this will be, will investigate further if it persists

**Comment by JThiner1997** [comment]
descriptions are still missing

**Comment by fanfare** [comment]
just so theres no confusion are you referring to the text like in this picture as the description https://i.imgur.com/fFpzqYO.png or something else, because i notice it goes away sometimes and will try and further figure out something more consistent

**Comment by JThiner1997** [comment]
I meant like this 
![Untitled](https://user-images.githubusercontent.com/49927694/97380932-6f87c400-189e-11eb-8165-7c3fad808156.jpg)
