### ISSUE TITLE
Some pictures aren't loading

### ISSUE THREAD

**Issue by JThiner1997** [fanfare/googleimagesrestored#58]
Some pictures are not loading on Google Images, can you please find out what's wrong?

**Comment by fanfare** [comment]
looks fine on my end, what should i search for to reproduce no pictures showing up

**Comment by JThiner1997** [comment]
It was probably another extension that caused it.

**Comment by JThiner1997** [comment]
Some pictures are not loading high-quality versions, like this
![Untitled](https://user-images.githubusercontent.com/49927694/99444575-6496e100-28ea-11eb-8977-27055ca22670.jpg)

**Comment by JThiner1997** [comment]
And implement it as a bug fix for version 0.3.2.

**Comment by fanfare** [comment]
thats always been a thing, if the high quality version is linked to either a non existent file (linkrot), or if its forbidden, or some other problem (like facebook urls etc) it just does that.

**Comment by JThiner1997** [comment]
I meant that they are having slower response times
