### ISSUE TITLE
still can't work

### ISSUE THREAD

**Issue by Luciushy** [fanfare/googleimagesrestored#6]
![](https://lh3.googleusercontent.com/fhG7R8ytFAfDN-0UDodBgOOBzCdNRFN5cmQ75mShw9Jk9RR_6lvGAlyfnwwOy48DtMncA76Dc7DKR9zKZKYf4Cbf_XYoNV4aVtZc9dvzS6ca8s_vSNfDLIJdMIq3WsnqZXEtDDiVFsbbPrjdzQaKBnSkw2LitQRp_ikEZ-aHX2_U71pU8R4CnhYn4eznD-LCQYAQxBsNdIOINugkKV0hckQ9Lu2q2KPhdmqmM-RQ15ZBqNSDiyWfRX5T-f8tmrt3OtAQMw5cKdoL3Nar_h0SSthbWvMNLehFsKaHi4zxm7-POw8VXBhbQFqLsq9jdqQBK3WwtGD9V7WLSRt2iI5k9G9ctbY3bVnv3qa1lOp8TRoJs8X-HFD4MRzBwFdL7Rk_vhIoR7ERYv6rs-L3SVvin6ft3dP8_kPy5JTFe4_AqD7hZk2lfrWk-S-34Fj3BcaVWfYLhCS1EDe8HU3wdMARQCyH9KAWRlifcDdiNe8MgZQ8T0KXHD4pKFvy2HegSjNvkmtjmH7cTIL7WTJCuiW4gDEFyXNvR8qX3g2y3pECpGhzU161oV3MzPM0roiozK8F11_5dpmam-0A38fB40gXtWStHjWcB2CLgdIvZ0HaKN0ZopAWgPHpiT4dMaMpwcyYBIF0BaBaovSSDZJBKrbsUXqm-BdVqNiOPm1Pu8DcPeSeaZD2K7x1WzfPVgbKlNbd-f_6zfzBkWyF_eRujm6Qb5Vg9NpeyLl9xNH6tlwBbFhk3tgFFCsrJPpMf7QvGguq9t9rzXq3tmlZhPHRhioSg5gE55KWlo7M2hRA7Ns1GwZLYALZbDH89D-H=w2499-h1181-no)

![](https://lh3.googleusercontent.com/D2TjumCOshAbCl-SXdv9eq9aMg3vbTSo9jN4gCWwltGs1MhqrxMwvC7R8caSkLRtybJ7u7N5-SIt_tOaf7FfpyjJ9Ivbn5dmYJSGMAImp2L3KdtIhErIgcsML2E0i5nUs3Ij8IvwXunxktl66MpufTg7Ur1UB9C69XBI9qHqIpAVMotO3t2jwn4xh_YXNBPqJd4yaOvUd3L04f-r4An1QNBHBLQeb5vyMJWMiHO0I_7qNlov3AG17VA5c1qtnivmQvGmn8KmgEVcWfmQRPmqcry2Y9Fb60H7VyOPq0-i0AYnMfv3-dZZlJdHQBNsRldKmROy-Kz9L3JCkGgWE2kghGb9rBC1Zzd9TnmMlnHpnpKJgUf5q_S3vXdaYDx4stxinWDHTqvDPZI9lDGA7cnupriHTUGyg95EfyY29TOshnKyU7VB2onMt9fJxUmrmPEBbu6s5tfEZAbCikYGpdDq4ckJ1PGMx2hKaZgQey03jpKO03szN-6xcWzaNl7cWBehdIniq-rILIQzVU4ZtSaPm_qWrrSKEN9OoU6bIpPW04ZEUbWoK30MM6417cfHY1d7_JdGHO3YmxFOJHLxitu5Hstl1vC5ywRm8V2A9v_szzVp7U0tLbV7y4GCQ4-62aU3o6jhyTfo-3pir0AHH5ECauBr1dmFxwQ8=w2550-h1267-no)
i failed to return to the old version and the *view image* button still diappears.but when i turn on the incognito mode,i'm so confused and curious why this happened to me.

**Comment by fanfare** [comment]
Having trouble understanding your issue --
Are you saying that the extension doesn't work in Incognito mode?
if so, right click the extension icon, click manage extensions, scroll down to 'allow in Incognito mode' -- 
If I'm misunderstanding, please tell me what steps are necessary to replicate your issue. Thanks

**Comment by fanfare** [comment]
Nevermind - I saw your comment in the chrome extension review -- so it *only* works in Incognito mode.
A user on reddit had a simliar issue -- they resolved it by clearing their cache/cookies and then logging back in. It then started to work.
I have absolutely no idea why this happens.. but I hope clearing the cookies fixes it for you.
