### ISSUE TITLE
"Related Images" is empty

### ISSUE THREAD

**Issue by iFreilicht** [fanfare/googleimagesrestored#61]
![image](https://user-images.githubusercontent.com/9742635/104837553-a249c300-58b5-11eb-9767-771c34a8033a.png)

Using Firefox 84.0.2 on Manjaro.

**Comment by fanfare** [comment]
I was able to replicate this issue on non-US google domains, e.g. google.de and am investigating a workaround

**Comment by fanfare** [comment]
the issue should be resolved in version [0.3.4](https://github.com/fanfare/googleimagesrestored/releases/tag/0.3.4). the extension was assuming the TLD was .com, thanks for reporting this issue.
i've published an update to the chrome web store and mozilla addons - it should be available shortly
