### ISSUE TITLE
Missing image with faviconizegoogle

### ISSUE THREAD

**Issue by gabri25ele** [fanfare/googleimagesrestored#63]
I use this script
https://greasyfork.org/en/scripts/7664-faviconizegoogle/code

With the last update I see that

![sshot-1](https://user-images.githubusercontent.com/33927879/107512917-c3958a80-6ba7-11eb-83fb-72ed3b6d246c.png)

no image.

is there a problem of googleimagesrestored?

**Comment by fanfare** [comment]
unfortunately i can't vouch for the extension working well with other extensions that I don't have any control over
