### ISSUE TITLE
Very inconvenient to use

### ISSUE THREAD

**Issue by ruboard** [fanfare/googleimagesrestored#64]
not very convenient to use. each time you have to scroll to view the thumbnails from above. it would be more convenient if the main window was moved down, leaving the ability to fully see the rest of the miniatures from above
like on a picture:
https://images2.imagebam.com/99/43/05/cada181370854454.jpg
(sorry for bad English)

**Comment by fanfare** [comment]
that isn't how the old format was. this extension tries to be as close to the old format as possible.

**Comment by ruboard** [comment]
contrary to convenience?
