### ISSUE TITLE
What does this line do?

### ISSUE THREAD

**Issue by Pccode66** [fanfare/googleimagesrestored#65]
https://github.com/fanfare/googleimagesrestored/blob/8e77eb0e4314df9a64c8d3df2eb04c9868795085/js/main.js#L11
What does this line do? I'm curious to know, it looks very minified.

**Comment by fanfare** [comment]
The function works like the `window.atob()` function, but with support for unicode strings. There is another function, `btoaUTF8` in [js/ipc.js](https://github.com/fanfare/googleimagesrestored/blob/8e77eb0e4314df9a64c8d3df2eb04c9868795085/js/ipc.js) (the first line) that works like `window.btoa()` but with support for unicode also. I had been trying to use the native window `btoa` and `atob` functions, but it fails when the HTML being parsed contains emojis, etc. This was used as a resource:

https://stackoverflow.com/questions/30106476/using-javascripts-atob-to-decode-base64-doesnt-properly-decode-utf-8-strings
