### ISSUE TITLE
"Related images" broken

### ISSUE THREAD

**Issue by fireattack** [fanfare/googleimagesrestored#66]
Steps to reproduce:

1. Open any single image link, such as https://images.app.goo.gl/q2kGbJXEjyZLCXz69 (you can get such link by clicking "share" button on any search result.)
2. Click any of the related images below

**Comment by fanfare** [comment]
thanks for catching that - i can replicate it here. I never really encounter these standalone 'share' pages so I'm just now seeing this problem. it seems simply removing `*imgres?*` from `include_globs` in the `manifest.json` file will remedy the situation but i need to test it out to make sure that doesn't affect the normal image searches.

**Comment by fanfare** [comment]
should be fixed in [0.3.7](https://github.com/fanfare/googleimagesrestored/releases/tag/0.3.7)
