### ISSUE TITLE
Firefox support.

### ISSUE THREAD

**Issue by Vilmodao** [fanfare/googleimagesrestored#68]
Hi,
Thanks for the nice extension. 
What about Firefox? I can't find any information about this. Did you stop Firefox support? Why?
Thanks.

**Comment by fanfare** [comment]
Hi - there used to be a firefox extension, but it was [removed](https://github.com/fanfare/googleimagesrestored/commit/8e77eb0e4314df9a64c8d3df2eb04c9868795085#commitcomment-48276522) after Mozilla's started to require 2FA to log into their site. This extension can be loaded manually in [Firefox Developer Edition](https://www.mozilla.org/en-US/firefox/developer/) - after installing open `about:config` and set `xpinstall.signatures.required` to `false`.

**Comment by Sxderp** [comment]
If willing, I'll publish it on Mozilla. I'm not sure how transfer of the extension ownership would work so that users could continue updating seamlessly from old install...

**Comment by fanfare** [comment]
I had the extension signed on a seperate firefox account; this will run on any version.

https://github.com/fanfare/googleimagesrestored/releases/download/0.3.8/google_images_restored-0.3.8-fx.xpi

**Comment by Vilmodao** [comment]
Thank you. Great extension.
