### ISSUE TITLE
Keyboard arrows don't work on drop down suggestions

### ISSUE THREAD

**Issue by sabbath7991** [fanfare/googleimagesrestored#7]
After searching for an image, the drop down suggestions can't be highlighted when using the Up and Down arrows on the keyboard. I'm using the latest version of Firefox and also doesn't work on the latest version of Chrome.

**Comment by fanfare** [comment]
Thanks - should be resolved in version 0.1.0.

**Comment by sabbath7991** [comment]
Thanks for the quick fix
