### ISSUE TITLE
[Question] Why is this great add-on extension not available on the Firefox Addons page?

### ISSUE THREAD

**Issue by idgas01** [fanfare/googleimagesrestored#73]
I was just bookmarking the installation pages of my Firefox add-on extensions, and I noticed that the page for yours isn't working:
https://addons.mozilla.org/en-US/firefox/addon/google-images-restored/

Did you make the decision to take it down (if so why?) or did Firefox remove it?  Either way, I don't understand it because your extension is wonderful.

I would not be able to use a lot of popular services or even Microsoft if it wasn't for guys like you.  I don't see how anyone could use Google or Microsoft if it wasn't for you three guys.

You restored Google Images with your add-on extension.
Aligo (later supported by bleep DrWonky) restored Google Search Results with the Better Google userscript.
RaMMicHaeL gave us the 7+ Taskbar Tweaker program that lets us "don't combine" grouped small taskbar buttons.

**Comment by fanfare** [comment]
thanks for the heads up, i resubmitted it using unminified functions (it seems like it had been removed because two helper functions were minified, so I submitted the full source code in the file) and it's back online now.
