### ISSUE TITLE
View More button

### ISSUE THREAD

**Issue by DDGYhaoo4354** [fanfare/googleimagesrestored#79]
View More button Is gone Or missing. its Kind of a important Feature of the old Google Images, 
is there anyway to add it back?
![Before](https://user-images.githubusercontent.com/114318399/192122819-237989e4-0743-4538-886f-e1864417427a.png)
![After](https://user-images.githubusercontent.com/114318399/192122833-f672dce5-01f8-4fac-8d88-a8bd80476417.png)

**Comment by fanfare** [comment]
thanks for the heads up, would you mind trying version [0.4.6](https://github.com/fanfare/googleimagesrestored/releases/tag/0.4.6) to see if that fixes it on your end
