### ISSUE TITLE
Show the image dimensions when hovering over the preview

### ISSUE THREAD

**Issue by VSuhas22** [fanfare/googleimagesrestored#8]
[This is how normal google images looks.](https://i.imgur.com/ZNtBL12.png)  
By using this extension, the Image dimensions don't appear when hovering over the image preview.  
Is this something that can be added?

**Comment by fanfare** [comment]
just added thumbnail hovering version 0.1.1. I'm currently unable to update it in the Chrome web store -- the last update is stuck on 'pending review' and I can't submit a new version right now for some reason.
