### ISSUE TITLE
View More Button Is Broken agian

### ISSUE THREAD

**Issue by DDGYhaoo4354** [fanfare/googleimagesrestored#80]
So it seems Shitty Google Changed something agian and it Broke The view more Button Some Images Work While Most don't.

![Picture1](https://user-images.githubusercontent.com/114318399/195517934-77d4c26a-7be8-41ef-9193-197be40bbe2b.png)
![Picture2](https://user-images.githubusercontent.com/114318399/195517938-6963d531-c40b-4232-a921-f7777140922b.png)

**Comment by fanfare** [comment]
what version are you using? i still see the 'view more' button on version 0.4.6, 
ill keep an eye out to see if it stops working again on my end.

**Comment by DDGYhaoo4354** [comment]
Am Using V0.4.6 But Somehow It broke. some images Show The View More Butten But Most Don't

**Comment by fanfare** [comment]
i dont see it on my end. is probably A/B testing. if it affects everyone globally ill take a look at it.
