### ISSUE TITLE
More Useless Changes

### ISSUE THREAD

**Issue by DDGYhaoo4354** [fanfare/googleimagesrestored#81]
Google Has made a UI change That Rounds The edges of the images and add Annoying text below it.
![Useless UI Change](https://user-images.githubusercontent.com/114318399/196577841-93681f8d-a711-48ca-bf22-54e77c1751ca.png)

**Comment by fanfare** [comment]
i dont see this on my end. looks like A/B testing. if they roll it out globally ill see what i can do

**Comment by DDGYhaoo4354** [comment]
Well Its Seems They Rolled It Out To Every One Now.

**Comment by DDGYhaoo4354** [comment]
Well It Seems They Rolled It Out Completely Now, Tried Everything to Remove It Doesn't Work. It Sucks Now
