### ISSUE TITLE
It happened Again 

### ISSUE THREAD

**Issue by DDGYhaoo4354** [fanfare/googleimagesrestored#84]
Google Seems to have removed To the view more button Also am using latest Version 0.4.9
![Screenshot (1866)](https://user-images.githubusercontent.com/114318399/206627924-7050c1fb-9fe0-47b4-b4d4-ef70cfe31d26.png)

**Comment by fanfare** [comment]
can confirm, thanks. they changed something on the back end. ill look into it.

**Comment by fanfare** [comment]
identified the issue, it should be fixed in [`0.5.0`](https://github.com/fanfare/googleimagesrestored/releases/tag/0.5.0), the published release should be in both the firefox addon and chrome web store as soon as its approved.
