### ISSUE TITLE
Some Pictures are not shown

### ISSUE THREAD

**Issue by derrapf** [fanfare/googleimagesrestored#85]
Since some month I have the issue that some pictures are not shown. If you klick on it nothing happens.
Example: Search for "Leni Klum" and klick on the third picture.
It's the picture with the URL  https://www.watson.de/unterhaltung/prominente/916862240-leni-klum-irritiert-mit-neuem-party-bild-soll-das-sexy-sein
I am using Firefox 107.0.1

BR Ralf

**Comment by fanfare** [comment]
it's working for me; the firefox extension was upgraded/migrated to a different extension within the past month. uninstall the google images restored version you have and then install this one: https://addons.mozilla.org/en-US/firefox/addon/google-images-restored-backup/

**Comment by derrapf** [comment]
Great
Works. Thanks
