### ISSUE TITLE
Possibility to allow the extensions functionality but in the new side view layout. 

### ISSUE THREAD

**Issue by csaltzberg** [fanfare/googleimagesrestored#86]
Is it possible to allow the extensions functionality (viewing the full size image and linking directly to it) but in the new side view layout that google has been using?

The side view layout allows for an easy comparison between the item you have selected and the rest of the search results (as it stays fixed position on the screen).

Current layout (example) with extension enabled
![image](https://user-images.githubusercontent.com/60652529/207749624-51bf396a-9301-4017-ab24-3c72718316d8.png)

New layout (example) option request for side layout
![image](https://user-images.githubusercontent.com/60652529/207749545-efe24ed1-c957-4c1f-b701-2cabfe6dfd36.png)

_Thanks for the work you do to allow us to have the options that google should have not changed or allows us the options to have!_

-Carl

**Comment by fanfare** [comment]
if you only want something like the 'view image' button, uninstall the _google images restored_ extension and use something like this [https://chrome.google.com/webstore/detail/view-image/jpcmhcelnjdmblfmjabdeclccemkghjk?hl=en](https://chrome.google.com/webstore/detail/view-image/jpcmhcelnjdmblfmjabdeclccemkghjk?hl=en) which will add a 'view image' button to the right side panel
