### ISSUE TITLE
Ctrl+Click to open new tab doesn't work on Google logo (top left corner) on images tab only

### ISSUE THREAD

**Issue by literaldehyde** [fanfare/googleimagesrestored#87]
Right click -> Open link in new tab works fine, but Ctrl+Click just shows/hides image sizes on all images. Not a big deal, but kinda annoying.

Inspect element shows " forceshowgishoverinfo" being added to the  `<body . . . class = "" . . . >`  section

Tested in clean version of Google Chrome w/ new (not signed in) browser account. No other extensions.

Chrome Version 110.0.5481.78 (Official Build) (64-bit)
Google Images Restored Version 0.5.0

![1](https://user-images.githubusercontent.com/37944384/218291200-c86d4f76-0626-47cf-ae60-7ff2fd9eb214.jpg)

**Comment by fanfare** [comment]
this is a result of someone else requesting the ability to see thumbnail sizes, ctrl+click on the logo was just a solution to make that happen. if you want to get rid of it, remove the following code from `main.js`

      let siclick = document.querySelector(`a.F1hUFe`)
       if (siclick) {
         siclick.addEventListener('click', (e)=>{
           if (e.ctrlKey) {
             e.preventDefault()
             e.stopPropagation()
             document.body.classList.toggle('forceshowgishoverinfo')
           }
         })
       }
