### ISSUE TITLE
Feature request: Easy access to advanced settings.

### ISSUE THREAD

**Issue by akovia** [fanfare/googleimagesrestored#88]
Hi, and thank you for this extension. 

I am a power user of google images, and I'm convinced that they really don't want people using this feature anymore by the way they keep "improving" it to the point that it is almost useless. Possibly due to copyright issues, but it's certainly something. (the results even seem less relevant now)

They've buried access to the advanced options, and wondered if you are able to make them more accessible with your extension. Even just a small cog that is placed by the tools button that takes you directly there, or exposing some of the advanced options directly on the main page would be outstanding.

![Google-images](https://user-images.githubusercontent.com/10238233/221957852-e907232a-a329-4dac-bec7-609173aa7270.jpg)

Either way, I appreciate your work and am glad someone is still trying to give us back [what we lost](https://fanart.tv/tutorials/search-images/).

Thanks!

**Comment by fanfare** [comment]
fwiw it isn't really buried too deep, just click the gear ![gear](https://i.jollo.org/pFqldf-J.png) and then click "advanced search"
