### ISSUE TITLE
Google changed the image method.

### ISSUE THREAD

**Issue by potona** [fanfare/googleimagesrestored#92]
Changed in a more inconvenient way.
I'd love to see an update if you can.

![1683463399383](https://user-images.githubusercontent.com/132824942/236678502-65044869-0008-4792-a6da-2e0c2c245fa7.png)

**Comment by fanfare** [comment]
not sure what this page is or where it is showing up. if it is related to 'google lens' by some chance i made an extension to bypass it, which is available here http://github.com/fanfare/disablegooglelens
