### ISSUE TITLE
Remove the tags icons in images thumbnails + Remove favicons at  , fix the "old" links format displays and mores

### ISSUE THREAD

**Issue by MossyMosMos** [fanfare/googleimagesrestored#95]
the "new" google seem to added or returned the tags icons in each images thumbnails now. could you remove them out? @fanfare

 
![imagestagsicon1](https://github.com/fanfare/googleimagesrestored/assets/126743138/4adb31c3-d4f5-45bd-ba4e-f9a4de956a27)

![imagestagsicon2](https://github.com/fanfare/googleimagesrestored/assets/126743138/20cd792d-416a-4ca6-97bb-b7f97e92e430)

![imagestagsicon3](https://github.com/fanfare/googleimagesrestored/assets/126743138/26790424-1b29-43f8-b7dd-e7473756e9b0)

![imagestagsicon4](https://github.com/fanfare/googleimagesrestored/assets/126743138/e6bbf4e9-eb14-4368-8f98-22fc77814eb4)

**Comment by fanfare** [comment]
just started happening on my end, i have a fix for it, some other stuff is changing right now (domains being removed again underneath the thumbnail) im gonna wait til the end of the day to make sure things are stable then ill push an update

**Comment by MossyMosMos** [comment]
> just started happening on my end, i have a fix for it, some other stuff is changing right now (domains being removed again underneath the thumbnail) im gonna wait til the end of the day to make sure things are stable then ill push an update

now it's happening again for me, these tags icons are back on me now

**Comment by MossyMosMos** [comment]
hey @fanfare we got many problems now, the favicons at images thumbnails titles are back, "an hour ago" and "a day ago" tags are back too, also the links texts formats are not properly display now. (should be become an old format like ".com") also when i click to see more related images the links aren't show properly as well. these need a lots of fixes now.
![imagesrestoredbroken](https://github.com/fanfare/googleimagesrestored/assets/126743138/0c75cccf-55f4-472f-a723-fd97331a8f36)

![imagesrestoredbroken2](https://github.com/fanfare/googleimagesrestored/assets/126743138/7dcd5791-09ed-4c20-acfe-58130362bdfe)

![imagesrestoredbroken3](https://github.com/fanfare/googleimagesrestored/assets/126743138/1b985b9a-2706-4f80-9b2f-3e7a685d25a7)

![imagesrestoredbroken4](https://github.com/fanfare/googleimagesrestored/assets/126743138/2d5f99cd-32dd-45d7-aef3-2dd9f16e1e25)

**Comment by MossyMosMos** [comment]
> hey @fanfare we got a lots of problems now, the favicons at images thumbnails titles are back, "an hour ago" and "a day ago" tags are back too, also the links texts formats are not properly display now. (should be become an old format like ".com") also when i click to see more related images the links texts aren't show properly as well. these need a lots of fixes now. !
> 

@fanfare could you fix these one too? this time, there are need a lots of fixes

**Comment by MossyMosMos** [comment]
after i updated into version 0.5.4 the tags icons in images thumbnails are still there. could you fix them by remove them out? @fanfare 

![updatedimagestags](https://github.com/fanfare/googleimagesrestored/assets/126743138/59104bb6-e69b-4cdf-a237-7aba23982aaf)
![updatedimagestags2](https://github.com/fanfare/googleimagesrestored/assets/126743138/690b4c27-c227-4339-98c1-d6c61bfc220f)
![updatedimagestags3](https://github.com/fanfare/googleimagesrestored/assets/126743138/b158abd8-8a87-4688-969d-c3e2b66dc8b9)
![updatedimagestags4](https://github.com/fanfare/googleimagesrestored/assets/126743138/6e0e7466-44e2-4ad6-85a4-2fa26cd950cb)
![updatedimagestags5](https://github.com/fanfare/googleimagesrestored/assets/126743138/48943aa6-4605-4ad2-aa29-cdf39bba8bc9)
