### ISSUE TITLE
Tools sidebar

### ISSUE THREAD

**Issue by mzso** [fanfare/googleimagesrestored#97]
Hi!
What I really miss from the old layout is the tools sidebar, where I could change several option. Not only that but the new tools button on the top fails to deliver all the options the old layout had. I'm restricted to the ridiculously outdated small/medium/large options for a start.

**Comment by fanfare** [comment]
at one point i tried to implement something that gave the option to search with specific sizes, etc, but google kept changing things and it really became futile trying to keep it going; the last time i tried to do something with the toolbar i had trouble even getting it to work. i wish the old toolbar was available but its unfortunately just too much for me to try and make work, considering they can just change stuff at any moment
